In [2]:
import numpy as np
a = np.array([4,5,6,3,7,90,40])
b = a+5 
print(b)

[ 9 10 11  8 12 95 45]


In [3]:
a = np.array([4,5,6,3,7,90,40])
print(np.mean(a))

22.142857142857142


In [4]:
a = np.array([4,5,6,3,7,90,40])
print(a.ndim)

1


In [5]:
a = np.array([[4,5,6,3,7,90,40,41],
             [1,2,5,6,8,9,3,4]])
print(a)
print(a.ndim)
print(a.size)
print(a.shape)

[[ 4  5  6  3  7 90 40 41]
 [ 1  2  5  6  8  9  3  4]]
2
16
(2, 8)


In [6]:
a = np.arange(2,20,2)
print(a)

[ 2  4  6  8 10 12 14 16 18]


In [7]:
a = np.linspace(10,31,5)
print(a)

[10.   15.25 20.5  25.75 31.  ]


In [8]:
a  = np.arange(1,19).reshape(2,3,3)
print(a)
print(a.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
3


In [9]:
a = np.arange(11, 29, 2).reshape(3, 3)
print(a)

[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [10]:
a= np.array([10,20,30])
print(a[1])

20


In [11]:
a= np.array([10,20,30])
print(a.dtype)

int64


In [12]:
arr = np.array([4,5,60])
arr2 = np.array([1,2,3])
print(arr+arr2)
print(arr-arr2)
print(arr*arr2)
print(arr/arr2)
print(arr**arr2)

[ 5  7 63]
[ 3  3 57]
[  4  10 180]
[ 4.   2.5 20. ]
[     4     25 216000]


In [13]:
marks = np.array([10,20,40,70,80])
print(marks.sum())
print(marks.mean())
print(marks.max())
print(marks.min())

220
44.0
80
10


In [14]:
a = np.array([10, 20, 30])
b = np.array([40, 50, 60])
c = np.concatenate((a, b))
print(c)

[10 20 30 40 50 60]


In [15]:
a= np.arange(5,51,5)
print(a)

[ 5 10 15 20 25 30 35 40 45 50]


In [16]:
a = np.ones((4, 3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
a = np.linspace(0, 1, 5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [18]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
a = np.array([[10, 20, 30],
              [40, 50, 60]])
print("Shape:", a.shape)
print("Size:", a.size)
print("Dimensions:", a.ndim)
print("Data type:", a.dtype)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int64


In [20]:
a = [10, 20, 30, 40, 50]
b = np.array(a)
print(b)

[10 20 30 40 50]


In [21]:
a = np.arange(1, 17)
b = a.reshape(4, 4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [22]:
a = np.array([10, 20, 30, 40, 50])
print(a[::-1])

[50 40 30 20 10]


In [23]:
a = np.array([10, 20, 30, 40, 50])
print(a[2])

30


In [24]:
a = np.array([10,20,30,40,50,90])
middle_element = a[len(a)//2]
print(middle_element)

40


In [25]:
a = np.array([10, 20, 30, 40, 50])
print(a[a > 25])

[30 40 50]


In [26]:
a = np.array([10, -5, 20, -3, 30])
a[a < 0] = 0
print(a)

[10  0 20  0 30]


In [27]:
a = np.array([10,3,9,40,70,80])
print(a[a%3==0])

[3 9]


In [28]:
a = np.array([10,20,40,20,50,20])
print(np.where(a==20))

(array([1, 3, 5]),)


In [29]:
a= np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
a = np.full(5,4.7)
print(a)

[4.7 4.7 4.7 4.7 4.7]


In [32]:
a = np.array([[1, 2, 3], [4, 6, 7]])
b=a.flatten()
print(a)
print(b)

[[1 2 3]
 [4 6 7]]
[1 2 3 4 6 7]


In [33]:
a = np.array([[1, 2, 3], [4, 6, 7]])
print(a.ravel())
print(a)

[1 2 3 4 6 7]
[[1 2 3]
 [4 6 7]]


In [34]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a.sum(axis=0))
print(a.sum(axis=1))

[5 7 9]
[ 6 15]


In [35]:
a = np.random.rand(5)
print(a)

[0.73114691 0.83074475 0.5452187  0.21741328 0.35510682]


In [36]:
a = np.random.randint(5)
print(a)

0


In [37]:
a = np.array([10, np.nan, 30, 40])
print(np.nanmean(a))

26.666666666666668


In [38]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])           #Assigment 1
print(a)
print("ndim:", a.ndim)
print("shape:", a.shape)
print("dtype:", a.dtype)
print("itemsize:", a.itemsize)
print("size:", a.size)

[ 1  2  3  4  5  6  7  8  9 10]
ndim: 1
shape: (10,)
dtype: int64
itemsize: 8
size: 10


In [39]:
a = np.arange(0, 21, 2)
print(a)
print("Shape:", a.shape)

[ 0  2  4  6  8 10 12 14 16 18 20]
Shape: (11,)


In [40]:
a = np.linspace(5, 50, 10)
print(a)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [41]:
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [42]:
a= np.ones((4,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [43]:
a = np.full((2,5),7)
print(a)

[[7 7 7 7 7]
 [7 7 7 7 7]]


In [44]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [45]:
a = np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [46]:
a = np.random.rand(5)
print(a)

[0.87594627 0.21596846 0.62941501 0.26538458 0.85438284]


In [47]:
a = np.random.rand(3,3)
print(a)

[[0.26945208 0.37844458 0.21831317]
 [0.43966986 0.8335765  0.13628533]
 [0.38125882 0.83999975 0.15248685]]


In [48]:
a= np.array([1,2,3,4,5,6])
print(a)
print("ndim:",a.ndim)
print("shape:",a.shape)
print("size:",a.size)

[1 2 3 4 5 6]
ndim: 1
shape: (6,)
size: 6


In [49]:
a= np.random.randint(1,100, size=(2, 4))
print(a)
print("Data Type:",a.dtype)

[[29 59  3 79]
 [86 52 59 20]]
Data Type: int32


In [50]:
a = np.array([1, 2, 3, 4, 5])
b = a.copy()
b[0] = 100
print("Original array:", a)
print("Copy array:", b)

Original array: [1 2 3 4 5]
Copy array: [100   2   3   4   5]


In [51]:
b = np.array([1, 2, 3, 4, 5])
c = b.view()
c[0] = 8
print("Original array:", b)
print("Copy array:", c)

Original array: [8 2 3 4 5]
Copy array: [8 2 3 4 5]


In [52]:
a= np.arange(100,120)
print(a)
print("Shape:",a.shape)
print("Size:",a.size)

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119]
Shape: (20,)
Size: 20


In [53]:
a= np.linspace(0,1,15)
print(a)

[0.         0.07142857 0.14285714 0.21428571 0.28571429 0.35714286
 0.42857143 0.5        0.57142857 0.64285714 0.71428571 0.78571429
 0.85714286 0.92857143 1.        ]


In [54]:
a = np.ones((2, 3), dtype=int)
print(a)
print("dtype:", a.dtype)

[[1 1 1]
 [1 1 1]]
dtype: int64


In [55]:
a= np.zeros((3,3),dtype = float)
print(a)
print("Item Size:",a.size)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Item Size: 9


In [56]:
a = np.random.randint(0, 10, size=(2, 5))
print(a)
print("Shape:", a.shape)

[[8 0 2 8 5]
 [1 6 6 7 8]]
Shape: (2, 5)
